
8659it [00:00, 86559.75it/s]
8659it [00:00, 86559.75it/s]Traceback (most recent call last):
  File "agent.py", line 165, in <module>
    torch.save(tgt.state_dict(), f"models/{step_num}.pth")
  File "F:\Coding Practice\Python\env\lib\site-packages\torch\serialization.py", line 376, in save
    with _open_file_like(f, 'wb') as opened_file:
  File "F:\Coding Practice\Python\env\lib\site-packages\torch\serialization.py", line 230, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "F:\Coding Practice\Python\env\lib\site-packages\torch\serialization.py", line 211, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: 'models/5051.pth'